blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('posts.urls', namespace="posts")),
    url(r'^comments/', include('django_comments.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list/$', views.post_list, name="list"),
    url(r'^create/$', views.post_create, name="create"),
    url(r'^signup/$', views.usersignup, name="signup"),
    url(r'^login/$', views.userlogin, name="login"),
    url(r'^logout/$', views.userlogout, name="logout"),
    url(r'^detail/(?P<slug>[-\w]+)/$', views.post_detail, name="detail"),
    url(r'^update/(?P<slug>[-\w]+)/$', views.post_update, name="update"),
    url(r'^delete/(?P<slug>[-\w]+)/$', views.post_delete, name="delete"),
    url(r'^like_button/(?P<post_id>[\d]+)/$', views.like_button, name="like_button"),
]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class Post(models.Model):
	author = models.ForeignKey(User, default=1)
	title = models.CharField(max_length=100)
	image = models.ImageField(upload_to="blog_images",null=True, blank=True)
	slug = models.SlugField(unique=True, null =True)
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField()
	timestamp = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"slug": self.slug})

	class Meta:
		ordering = ['title']


def post_receiver(sender,instance, *args, **kwargs):
	if not instance.slug:
		slug=slugify(instance.title)
		qs = Post.objects.filter(slug=slug).order_by("-id")
		exists = qs.exists()
		if exists:
			slug = "%s-%s"%(slug, instance.id)
		instance.slug = slug
		instance.save()


post_save.connect(post_receiver, sender=Post)

class Like(models.Model):
	user = models.ForeignKey(User) 
	post = models.ForeignKey(Post)
	

# slug = slugify(instance.title)
	# if new_slug is not None:
	# 	slug = new_slug
	# qs = Post.objects.filter(slug=slug)
	# exists = qs.exists()
	# if exists:
	# 	new_slug = "%s-%s"%(slug, instance.id)
	# 	return create_slug(instance, new_slug=new_slug)
	# return slug 


# def post_receiver(sender, instance, *args, **kwargs):
# 	if not instance.slug:
# 		instance.slug = create_slug(instance)

posts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title', 'content', 'image', 'draft', 'publish']

		widgets={
		'publish': forms.DateInput(attrs={"type": "date"})


		}

class UserSignUp(forms.ModelForm):
	class Meta:
		model = User 
		fields = ['username','password']

		widgets={
		'password': forms.PasswordInput()
		}

class UserLogin(forms.Form):
	username = forms.CharField(required=True)
	password = forms.CharField(required=True, widget=forms.PasswordInput())

posts/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import PostForm
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from urllib.parse import quote
from django.http import Http404, JsonResponse
from django.utils import timezone
from django.db.models import Q
from .forms import PostForm, UserSignUp, UserLogin
from django.contrib.auth import authenticate, login, logout



def usersignup(request): 
	context = {}
	form = UserSignUp()
	context['form'] = form
	if request.method == "POST":
		form = UserSignUp(request.POST)
		if form.is_valid():

			user = form.save(commit=False)
			username = user.username
			password = user.password
			user.set_password(password)
			user.save()
			auth_user = authenticate(username=username, password=password)
			login(request, auth_user)

			return redirect("posts:list")
		messages.error(request, forms.errors)
		return redirect("posts:signup")
	return render(request,'signup.html', context)

def userlogin(request):
	context = {}
	form = UserLogin()
	context['form'] = form
	if request.method == "POST":
		form = UserLogin(request.POST)
		if form.is_valid():
			
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']

			auth_user = authenticate(username=username, password=password)
			
			if auth_user is not None:
				login(request,auth_user)
				return redirect("posts:list")
			
			messages.warning(request, "Wrong username/password combination. Please try again.")
			return redirect("posts:login")
		messages.warning(request, form.errors)
		return redirect("posts:login")
		
	return render(request,'login.html', context)


def post_list(request):
	today= timezone.now().date()
	if request.user.is_staff or request.user.is_superuser:
		obj_list = Post.objects.all()
	else:
		obj_list = Post.objects.filter(draft=False).filter(publish__lte=today)
	
	query= request.GET.get("q")
	if query:
		obj_list = obj_list.filter(
			Q(title__icontains=query)|
			Q(content__icontains=query)|
			Q(author__first_name__icontains=query)|
			Q(author__last_name__icontains=query)|
			Q(author__username__icontains=query)
			).distinct() 

	paginator = Paginator(obj_list, 5) 

	page = request.GET.get('page')
	try:
		p_objects = paginator.page(page) 
		
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		p_objects = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		p_objects = paginator.page(paginator.num_pages)

	
	context = {
		"post_list": p_objects,
		"today" : today,
	}
	return render(request, 'post_list.html', context)


def post_detail(request, slug):
	obj = get_object_or_404(Post, slug=slug)
	date = timezone.now().date()
	if obj.publish > date or obj.draft:
		if not (request.user.is_staff or request.user.is_superuser):
			raise Http404

	if request.user.is_authenticated():
		if Like.objects.filter(post=obj, user=request.user).exists():
			liked = True
		else:
			liked = False

		post_like_count = obj.like_set.all().count()

		

	context = {
		"instance": obj,
		"like" : liked,
		"like_count" : post_like_count,
		
	}
	return render(request, 'post_detail.html', context)

def post_create(request):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404 
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False)
		obj.author = request.user
		obj.save()
		messages.success(request, "Object created.")
		return redirect("posts:list")
	context = {
		"form":form,
	}
	return render(request, 'post_create.html', context)


def post_update(request, slug):
	if not (request.user.is_staff or request.user.is_superuser):
		raise Http404 
	post_object = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=post_object)
	if form.is_valid():
		form.save()
		messages.success(request, "Object updated.")
		return redirect("posts:list")
	context = {
		"form":form,
		"post_object":post_object,
	}
	return render(request, 'post_update.html', context)


def post_delete(request, slug):
	if not (request.user.is_superuser):
		raise Http404 
	Post.objects.get(slug=slug).delete()
	messages.warning(request, "Object deleted. ")
	return redirect("posts:list")

def userlogout(request):
    logout(request)
    return redirect("posts:login") 

def like_button(request, post_id):
	obj = Post.objects.get(id=post_id)

	like, created = Like.objects.get_or_create(user=request.user, post = obj)

	if created:
		action="like"
	else:
		action="unlike"
		like.delete()

	post_like_count = obj.like_set.all().count()
	context = {
	"action": action,
	"like_count": post_like_count,
	}
	return JsonResponse(context, safe=False)



	

posts/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<style>

h1{
	font-size: 38px;
	
}

body {
	background-color: pink;
}
</style>

	<title>
		{% block head_title %}

		{% endblock head_title %}
	</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/posts.css' %}">

</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
<ol class="breadcrumb">
  <li><a href="{% url 'posts:list' %}">List</a></li>
  <li><a href="{% url 'posts:create' %}">Create</a></li>
  <li><a href="/admin">Go to admin</a></li>
  {% if not user.is_authenticated %} 

      <li><a href="{% url 'posts:login' %}">Login</a></li>

  {% endif %}
  

 
  <li>
  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Posts <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
  	{% for iter in post_list %}
    <li><a href="{{iter.get_absolute_url}}">{{iter.title}}</a></li>
   	{% endfor %}
   	</ul></li>
   	
   	<li>
 <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Update Post <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
  	{% for iter in post_list %}
    <li><a href="{% url 'posts:update' slug=iter.slug %}">{{iter.title}}</a> </li>
    {% endfor %}
       	</ul>
   	</li>
    <li>
    {% if  request.user.is_authenticated %}
        <li><a href="/admin/auth/user">{{request.user}}</a></li>
        <li><a href="{% url 'posts:logout' %}">Logout</a></li>
        {% else %}
        
     {% endif %}
        </li>



  </ol>
</div></li>
</ol>
</nav>
<br><br><br>

<h1>здравствуйте</h1>

<body>
{% include 'facebook_comments.html' %}
{% include 'messages.html' %}



<div class="container">
{% block content %}


{% endblock content %}
</div>

<script src="{% static 'js/jquery-3.2.1.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

posts/templates/django_comments.html
{% load comments %}




{% get_comment_list for instance as comments %}

		{% for comment in comments %}
	<div class="alert alert-info" role="alert">{{comment.user_name}} said: {{comment.comment|linebreaks}}</div>

		{% endfor %}

		
		{% get_comment_form for instance as form %}
		{% if request.user.is_authenticated	%}
		<form action="{% comment_form_target %}"method="POST">
		{% csrf_token %}
		
			<input type="hidden" name="name" value"{{request.user.username}}">
			<input type="hidden" name="email" value"{{request.user.email}}">
			<textarea type="text" class="form-control input-lg "name="comment"> </textarea>
			{{form.content_type}}
			{{form.object_pk}}
			{{form.timestamp}}
			{{form.security_hash}}
			<br>
			<input type="hidden" name="next" value="{{instance.get_absolute_url}}">
			<input type="submit" name="submit" class= "btn btn-primary">	

		</form>
		{% else %}
		<a href= "{% url 'posts:login' %}"> Please click this link to log in order to comment.</a>
		{% endif %}

posts/templates/facebook_comments.html
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

posts/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Login{% endblock head_title %}

{% block content %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
	<form method="POST" action="{% url 'posts:login' %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="Login" class="btn btn-info">
	</form>
	</div>
	</div>
	
{% endblock content %}

posts/templates/messages.html
{% if messages %}

<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class=" alert alert-{{ message.tags }}"{% endif %}>
	<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
	</button>
    {{ message }}

    </div>
    {% endfor %}
</div>
{% endif %}

posts/templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Create{% endblock head_title %}

{% block content %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
	<form action="{%url 'posts:create' %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="Create Post">
	</form>
	 </div>
	</div>
{% endblock content %}

posts/templates/post_detail.html
{% extends "base.html" %}
{% load urllify %}
{% load crispy_forms_tags %}

{% block head_title %}Detail{% endblock head_title %}

{% block content %}
	<div class="col-sm-6 col-sm-offset-3">

		<div class="thumbnail">
		{% if instance.image %}
      <img src="{{instance.image.url}}" class="img-responsive">
      {% endif %}
      <div class="caption">
        <h3>{{instance.title}}<small>{{instance.publish|timesince}} ago </small></h3>
        <p>{{instance.content |linebreaks|truncatechars:10}}</p>

        Author: {{instance.author.username}}
        <p>
	        
	        <a href="{% url 'posts:update' slug=instance.slug %}" class="btn btn-success">Update</a>
	        <a href="{% url 'posts:delete' slug=instance.slug %}" class="btn btn-danger">Delete</a>
        </p>
        <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
		Share on Facebook
		</a>

		<a href="https://twitter.com/home?status={{instance.content|urllify|truncatechars:50}}%20{{request.build_absolute_uri}}">
		Share on Twitter

		</a>

		<a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{instance.title|urllify}}&summary={{instance.content.urllifyfy}}&
		source={{request.build_absolute_uri}}"> 
		Share on Linkedin
	</a>
        </div>
        <div class="fb-like" data-href={{request.build_absolute_uri}} data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
     <div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5"></div>

		<!--<button class="btn" onclick="ajax_like()">
		<span id="likes_count">{{like_count}}</span>
		<span id = "heart" class="glyphicon glyphicon-heart {% if liked %}text-danger{% endif %}" aria-hidden="true" ></span>
		</button>

        {% include "django_comments.html" %} -->

		
      </div>
    </div>
  
<br>
	

	<a href="{% url 'posts:list' %}">Go back to list</a>

	<script> 
	function ajax_like()
	{
	console.log("Like/Unlike clicked!");
	$.ajax({
		type: 'GET',
		
		url: "{% url 'posts:like_button' post_id=instance.id %}",
		
		error: function(){
		console.log("I laugh the laugh of an axe-wielding madman.");}		
		,
		
		success: function(data){

			$("#likes_count").text(data.like_count)

			if(data.action==="like"){
				$("#heart").addClass("text-danger")

			}
			else{
			$("#heart").removeClass("text-danger")	

			}
			
		} ,

	})

	}
	</script>
{% endblock content %}

posts/templates/post_list.html
{% extends "base.html" %}


{% block head_title %}List{% endblock head_title %}

{% block content %}

<div class = "row">
<form action="{% url 'posts:list' %}" method="GET">
  <input type="text" name="q" placeholder="Search posts here" value="{{request.GET.q}}">
  <input type="submit" value="Search">

  <input type="reset"value="Clear"> 
  </form>
  <br>
{% for iter in post_list %}
	<div class = "col-sm-6">

		<div class="thumbnail">
		{% if iter.image %}
      <img src="{{iter.image.url}}" class="img-responsive">
      {% endif %}
      <div class="caption">
        <h3>{{iter.title}}<small>{{iter.publish|timesince}} ago </small></h3>
        {% if iter.draft %} <h4>Draft</h4> {% endif %}
        {% if iter.draft > today %} <h4>Draft</h4> {% endif %}
        <p>{{iter.content |linebreaks|truncatechars:10}}</p>
        <p>
        <a href="{% url 'posts:detail' slug=iter.slug %}" class="btn btn-primary">View</a>
        {%if request.user.is_superuser or request.user.is_staff %}
	        
	        <a href="{% url 'posts:update' slug=iter.slug %}" class="btn btn-success">Update</a>
	        <a href="{% url 'posts:delete' slug=iter.slug %}" class="btn btn-danger">Delete</a>
          {% endif %} 
        </p>
        </div>
      </div>
    </div>
  


	
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if post_list.has_previous %}
            <a href="?page={{ post_list.previous_page_number }}&q={{request.GET.q}}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.

        </span>



        {% if post_list.has_next %}
            <a href="?page={{ post_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

<p>
	<a href="{% url 'posts:create' %}" class="btn btn-primary">Create New Post?</a>
</p>

</div>


{% endblock content %}


{#{{x.get_absolute_url}}#}


    {#<div class="thumbnail">
      <img src="..." alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>...</p>
        <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
      </div>
    </div>
  </div>
</div>

<a href="{{x.get_absolute_url}}"><li>{{x.title}}</li></a> #}

posts/templates/post_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Update{% endblock head_title %}

{% block content %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
	<form method="POST" action="{% url 'posts:update' slug=post_object.slug %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="Update Post">
	</form>
	</div>
	</div>
	{# <a href="{% url 'posts:detail' post_id=iter.id %}" class="btn btn-success">Update</a> #}
{% endblock content %}

posts/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}Signup{% endblock head_title %}

{% block content %}
<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
	<form method="POST" action="{% url 'posts:signup' %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="Signup" class="btn btn-success">
	</form>
	</div>
	</div>
	
{% endblock content %}